spring:
  profiles:
    active: local
  application:
    name: alibaba-nacos-dubbo-producer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: local
        register-enabled: true
server:
  port: 8082
dubbo:
  scan:
    base-packages: com.xspace.nacos # 指定 Dubbo 服务实现类的扫描基准包
  protocol:
    name: dubbo
    port: -1
  registry:
    address: 127.0.0.1:8848
    register: true
    protocol: nacos
    parameters:
      namespace: local