spring:
  profiles:
    active: local
  application:
    name: alibaba-nacos-discovery-client-common
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: local
        register-enabled: true
server:
  port: 9091

