spring:
  application:
    name: spring-boot-cache
  profiles:
    active: local
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/micro-test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
jetcache:
  statIntervalMinutes: 1 # ???????0??????
  areaInCacheName: false # areaName??????key?????True
  expireAfterAccessInMillis: 30000 # # jetcache2.2???????????????????????????????????????0?????????
  local:
    default:
      type: linkedhashmap # ??????linkedhashmap?caffeine
      keyConvertor: fastjson # key??????????????fastjson, @see com.alicp.jetcache.support.FastjsonKeyConvertor
      limit: 100 # ??????????????????local?????????
  remote:
    default:
      type: redis # ??????redis?tair
      database: 1
      keyConvertor: fastjson
      valueEncoder: java # ???????????remote????????????java?kryo
      valueDecoder: java # ???????????remote????????????java?kryo
      expireAfterWriteInMillis: 5000 # ?????????????????
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  path: ./${spring.application.name}/log
